# Generated by Django 5.1.7 on 2025-04-17 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='time_limit',
            field=models.IntegerField(blank=True, help_text='Time limit in minutes', null=True),
        ),
    ]
