# Generated by Django 5.1.7 on 2025-04-17 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_exam_time_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='time_limit',
            field=models.IntegerField(help_text='Time limit in minutes'),
        ),
    ]
