# Generated by Django 5.1.7 on 2025-04-25 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_alter_question_question_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useranswer',
            name='selected_answer',
        ),
        migrations.AddField(
            model_name='useranswer',
            name='selected_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exams.option'),
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
