# Generated by Django 5.1.7 on 2025-04-26 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_remove_useranswer_selected_answer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_type',
        ),
    ]
